version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: finpay_postgres
    environment:
      POSTGRES_USER: finpay_user
      POSTGRES_PASSWORD: finpay_dev_1234
      POSTGRES_DB: finpay_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  finpay-app:
    build: .
    container_name: finpay_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/finpay_db
      - SPRING_DATASOURCE_USERNAME=finpay_user
      - SPRING_DATASOURCE_PASSWORD=finpay_dev_1234

volumes:
  postgres_data: