spring.application.name=wallet-service
spring.datasource.url=jdbc:postgresql://localhost:5432/finpay_db
spring.datasource.username=finpay_user
spring.datasource.password=finpay_dev_1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true