package com.finpay.wallet_service.service;

import com.finpay.wallet_service.entity.Role;
import com.finpay.wallet_service.entity.User;
import com.finpay.wallet_service.entity.Wallet;
import com.finpay.wallet_service.exception.BadRequestException;
import com.finpay.wallet_service.repository.UserRepository;
import com.finpay.wallet_service.repository.WalletRepository;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;

@Service
@RequiredArgsConstructor
public class UserService {
    private final UserRepository userRepository;
    private final WalletRepository walletRepository;
    private final PasswordEncoder passwordEncoder;

    @Transactional
    public void registerUser(String email, String password){
        // 1. Check if the user already exists
        if(userRepository.findByEmail(email).isPresent()){
            throw new BadRequestException("Email is already is use!");
        }

        // 2. Hash the password
        String hashedPassword = passwordEncoder.encode(password);

        User newUser = User.builder()
                .email(email)
                .password(hashedPassword)
                .role(Role.USER)
                .build();
// 3. Save the user first so they get an ID generated by the database
        User savedUser = userRepository.save(newUser);

// 4. Create a new empty wallet for them
        Wallet newWallet = new Wallet();
        newWallet.setUser(savedUser);
        newWallet.setBalance(BigDecimal.ZERO); // Start balance with ₹0.00
        walletRepository.save(newWallet);
    }
}
